// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FormTabsController from "./form_tabs_controller"
application.register("form-tabs", FormTabsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ToothSelectionController from "./tooth_selection_controller"
application.register("tooth-selection", ToothSelectionController)
