name: CI

on:
  push:
    branches: [ "main" ] # メインブランチにPushされた時に動く
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4

      - name: CI用のダミー.envファイルを作成
        run: touch .env

      - name: Dockerイメージのビルド
        run: docker compose build

      - name: データベースのセットアップ（テスト環境）
        run: |
          docker compose run --rm web bundle exec rails db:create RAILS_ENV=test
          docker compose run --rm web bundle exec rails db:migrate RAILS_ENV=test

      - name: RSpecの実行
        run: docker compose run --rm web bundle exec rspec